# Generated by Django 4.2 on 2023-05-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
    ]
